### ISSUE TITLE
The phaser site needs a link to this repo

### ISSUE THREAD

**Issue by EddieOne** [photonstorm/lazer#7]
I was like WTF is Lazer. I figured it was some proprietary thing being worked on. After reading the _Phaser in 2015 and beyond_ article, it seems more like the next phase of well Phaser. People should know as it's exciting to hear about the roadmap, philosophy, and past challenges.

**Comment by photonstorm** [comment]
I agree, and when we're in a position to pimp Lazer more I'll do that for sure, but it's a bit premature right to do so right now. I don't want to confuse people who are thinking of using Phaser ("should I use Lazer instead?"), because Lazer isn't ready for use _yet_.

**Comment by EddieOne** [comment]
Good point. Though people are already confused and [asking should I use Lazer instead](http://www.html5gamedevs.com/topic/22058-lazer-readiness/#comment-125676). Perhaps a little note in a prominent spot saying use Phaser for current projects and consider Lazer for future projects.

**Comment by cdelstad** [comment]
And some of us are already waiting to start near-future projects because it
sounds like Lazer should be close to being ready - based on things said
last year on the timelines, even with the caveat that its not ready until
its ready. Without anything solid to go on for timelines, we're all in a
state of flux about what to do. If we can even get a projected "Q1, 2018
for beta", or something to aim at, I think we'd all feel a lot better and
be able to leave breathing room for you guys to work. :)
We also know and respect that $$ paying jobs need to take priority and get
in the way of progress.
Anything to help us plan would be greatly appreciated.
Thanks again,
-Chad

**Comment by EddieOne** [comment]
Good example. I wouldn't wait for Phaser 3.0 to release unless your waiting on a specific feature. You should execute your ideas with the current best solution unless technically infeasible.
